<?php
/**
 * @file
 * Memcache Status module hooks.
 */

/**
 * Implements hook_menu().
 */
function memcache_status_menu() {
  $items['admin/reports/status/memcache'] = array(
    'title' => 'Memcache',
    'page callback' => 'memcache_status_memcache',
    'access arguments' => array('access memcache status'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'memcache_status.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_perm().
 */
function memcache_status_perm() {
  return array(
    'access memcache status',
  );
}
